### ISSUE TITLE
Nifi-Registry fails to start

### ISSUE THREAD

**Issue by 3n3a** [guimou/nifi-on-openshift#10]
Right after it says `Starting Nifi Registry on Port 18080` the pod has status `OOMKilled`.
Because of this the Registry prevents the rest of the pods from starting.

Ist there anything that can be done about this?

**Comment by guimou** [comment]
Have you tried increasing the memory available to the pod? It's not fixed in the StatefulSet definition (something I may modify in another release if people have issues), so it reverts to the default for your environment, which may not be enough.

**Comment by 3n3a** [comment]
> Have you tried increasing the memory available to the pod? It's not fixed in the StatefulSet definition (something I may modify in another release if people have issues), so it reverts to the default for your environment, which may not be enough.

No I haven't tried that. Gonna try that. Thanks so much

**Comment by 3n3a** [comment]
Thanks so much this works. I gave the container a limit of (cpu 100m and memory: 2Gi)
