### ISSUE TITLE
Fail deploy of Nifi Server because: badly formatted directory string

### ISSUE THREAD

**Issue by andres-mejia** [guimou/nifi-on-openshift#8]
Hi, maybe below experience can help to anyone ;)

I had a issue deploying the nifi statefulset of nifi.
I catched the error message: badly formatted directory string during the execution of  tls-toolkit.sh.

I found that ss-nifi.yaml have 

/opt/nifi/nifi-toolkit-current/bin/tls-toolkit.sh standalone \
                -n '$FQDN' \
                -C '$(admin_identity)' \
                -o '/opt/nifi/nifi-current/conf/' \
                -P env:PASS  \
                -S env:PASS  \
                --nifiPropertiesFile /opt/nifi/nifi-current/conf/nifi.properties

Checking the documentation of tls-toolkit for standalone:
https://nifi.apache.org/docs/nifi-docs/html/toolkit-guide.html

I found that correct use of **-C** argument is in DN format, by example:
bin/tls-toolkit.sh standalone -n 'nifi[01-10].subdomain[1-4].domain(2)' -C 'CN=username,OU=NIFI' 

Additionally I also found that -n '$FQDN'  is not printed correctly in the command, so I changed it to -n '$(hostname -f)' 

So I changed this two things in the script and finally the statefulset deployed as expected.

/opt/nifi/nifi-toolkit-current/bin/tls-toolkit.sh standalone \
                -n '$(hostname -f)' \
                -C 'CN=$(admin_identity),OU=NIFI' \
                -o '/opt/nifi/nifi-current/conf' \
                -P env:PASS  \
                -S env:PASS  \
                --nifiPropertiesFile /opt/nifi/nifi-current/conf/nifi.properties
              exec bin/nifi.sh run

**Comment by guimou** [comment]
That's really interesting as some people reported similar issues before. The odd thing is that I was never able to reproduce, and so far it was working quite well. I wonder why, especially as we use fixed versions of the container images. So anyway, I'll make some more tests with your syntax if it's indeed the proper way for the -C parameter, and make a new release if it's conclusive.

**Comment by guimou** [comment]
Implemented in #13 
Thanks a lot @andres-mejia !
